graph TD

    titleBefore[<b>Before</b>]
    titleBefore --> ApplicationBefore;
    style titleBefore fill:#FFF,stroke:#FFF;
    linkStyle 0 stroke:#FFF,stroke-width:0;

    titleAfter[<b>After</b>]
    titleAfter --> ApplicationAfter;
    style titleAfter fill:#FFF,stroke:#FFF;
    linkStyle 0 stroke:#FFF,stroke-width:0;

    ApplicationBefore[Application] -->BookLoader;
    BookLoader --> DatabaseBefore[OldDatabase];

    ApplicationAfter[Application] --> ValidatingBookLoader;
    ValidatingBookLoader -->
    OldBookLoader[BookLoader];
    ValidatingBookLoader -->
    NewBookLoader[BookLoader];
    OldBookLoader --> OldDatabase;
    NewBookLoader --> NewDatabase;
